"""Constants for the Reef ICP integration."""

DOMAIN = "reef_icp"

CONF_AQUARIUM_NAME = "aquarium_name"
CONF_AQUARIUM_VOLUME_L = "aquarium_volume_l"
CONF_SUPPLY_SYSTEM = "supply_system"
CONF_STOCKING_PROFILE = "stocking_profile"
CONF_REPORTS = "reports"

SUPPLY_SYSTEM_NONE = "none"
SUPPLY_SYSTEM_FAUNA_MARIN_BALLING_LIGHT = "fauna_marin_balling_light"
SUPPLY_SYSTEM_ATI_ESSENTIALS_PRO = "ati_essentials_pro"
SUPPLY_SYSTEM_TRITON_METHOD = "triton_method"
SUPPLY_SYSTEM_OCEAMO_DUO = "oceamo_duo"

SUPPLY_SYSTEM_NAMES = {
    SUPPLY_SYSTEM_NONE: "None / analysis only",
    SUPPLY_SYSTEM_FAUNA_MARIN_BALLING_LIGHT: "Fauna Marin Balling Light",
    SUPPLY_SYSTEM_ATI_ESSENTIALS_PRO: "ATI Essentials pro",
    SUPPLY_SYSTEM_TRITON_METHOD: "TRITON Method",
    SUPPLY_SYSTEM_OCEAMO_DUO: "Oceamo DUO",
}


STOCKING_PROFILE_MIXED_REEF = "mixed_reef"
STOCKING_PROFILE_SPS_DOMINANT = "sps_dominant"
STOCKING_PROFILE_LPS_DOMINANT = "lps_dominant"
STOCKING_PROFILE_SOFT_CORAL_DOMINANT = "soft_coral_dominant"
STOCKING_PROFILE_FISH_ONLY = "fish_only"
STOCKING_PROFILE_OTHER = "other"

STOCKING_PROFILE_NAMES = {
    STOCKING_PROFILE_MIXED_REEF: "Mixed Reef",
    STOCKING_PROFILE_SPS_DOMINANT: "SPS-dominant",
    STOCKING_PROFILE_LPS_DOMINANT: "LPS-dominant",
    STOCKING_PROFILE_SOFT_CORAL_DOMINANT: "Soft-coral dominant",
    STOCKING_PROFILE_FISH_ONLY: "Fish Only",
    STOCKING_PROFILE_OTHER: "Other / custom",
}

PROVIDER_OCEAMO = "oceamo"
PROVIDER_FAUNA_MARIN = "fauna_marin"
PROVIDER_ATI = "ati"

MAX_STORED_REPORTS = 100
